version: '3.7'

# Docker Networks
networks:
  niftsy_backend:
    external:
      name: niftsy_niftsy_backend

services:
  mint_api_service:
    image: "registry.gitlab.com/niftsy/swarm/apiservice_swarm:api"
    container_name: mint_api
    restart: always
    env_file: ./.env
    networks:
      - niftsy_backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    logging:
        options:
            max-file: "10"
            max-size: 2m
    restart: always