version: '3.7'

# Docker Networks
networks:
  niftsy_backend:
    external:
      name: niftsy_niftsy_backend

services:
  fastapi_service_stage:
    image: "registry.gitlab.com/niftsy/apiservice:api"
    container_name: fast_api_stage
    restart: always
    env_file: ./.env
    networks:
      - niftsy_backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    logging:
        options:
            max-file: "10"
            max-size: 2m
    restart: always
    secrets:
      - oracle_signer_passw 

  fastapi_service_test:
    image: "registry.gitlab.com/niftsy/apiservice:api"
    container_name: fast_api_test
    restart: always
    env_file: ./.env.test
    networks:
      - niftsy_backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    logging:
        options:
            max-file: "10"
            max-size: 2m
    restart: always
    secrets:
      - oracle_signer_passw     

secrets:
  # oracle_signer_passw:
  # External secrets are not available to containers created by docker-compose.
  #   external: true
  oracle_signer_passw:
    file: readme.not 
